[package]
name = "FamRust"
version = "0.1.0"
authors = ["aozkan <alper.ozkan.p@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "fam_rust"
path = "src/main.rs"
